--
-- PostgreSQL database dump
--

\restrict 8prvZOKtaogpL8f3nPMAP5NWxQNBRwvzhnhP00ngn2kwBl3VqZ83apyTH0wECmc

-- Dumped from database version 15.15 (Debian 15.15-1.pgdg13+1)
-- Dumped by pg_dump version 15.15 (Debian 15.15-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: maxsud
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO maxsud;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: maxsud
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: maxsud
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO maxsud;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: maxsud
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: maxsud
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO maxsud;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: maxsud
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: maxsud
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO maxsud;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: maxsud
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO maxsud;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: maxsud
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: maxsud
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: maxsud
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO maxsud;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: maxsud
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: maxsud
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO maxsud;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: maxsud
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: maxsud
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO maxsud;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: maxsud
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: maxsud
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO maxsud;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: maxsud
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: maxsud
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO maxsud;

--
-- Name: mainapp_company; Type: TABLE; Schema: public; Owner: maxsud
--

CREATE TABLE public.mainapp_company (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    logo character varying(100) NOT NULL,
    workers integer NOT NULL,
    CONSTRAINT mainapp_company_workers_check CHECK ((workers >= 0))
);


ALTER TABLE public.mainapp_company OWNER TO maxsud;

--
-- Name: mainapp_company_id_seq; Type: SEQUENCE; Schema: public; Owner: maxsud
--

ALTER TABLE public.mainapp_company ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mainapp_company_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mainapp_contactmessage; Type: TABLE; Schema: public; Owner: maxsud
--

CREATE TABLE public.mainapp_contactmessage (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    phone_number character varying(20) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    course_id bigint NOT NULL
);


ALTER TABLE public.mainapp_contactmessage OWNER TO maxsud;

--
-- Name: mainapp_contactmessage_id_seq; Type: SEQUENCE; Schema: public; Owner: maxsud
--

ALTER TABLE public.mainapp_contactmessage ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mainapp_contactmessage_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mainapp_course; Type: TABLE; Schema: public; Owner: maxsud
--

CREATE TABLE public.mainapp_course (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    banner character varying(100) NOT NULL,
    title_uz character varying(25) NOT NULL,
    title_en character varying(25) NOT NULL,
    title_ru character varying(25) NOT NULL,
    description_uz text NOT NULL,
    description_en text NOT NULL,
    description_ru text NOT NULL,
    price numeric(10,2) NOT NULL,
    duration integer NOT NULL,
    students integer,
    CONSTRAINT mainapp_course_students_check CHECK ((students >= 0))
);


ALTER TABLE public.mainapp_course OWNER TO maxsud;

--
-- Name: mainapp_course_id_seq; Type: SEQUENCE; Schema: public; Owner: maxsud
--

ALTER TABLE public.mainapp_course ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mainapp_course_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mainapp_courseabout; Type: TABLE; Schema: public; Owner: maxsud
--

CREATE TABLE public.mainapp_courseabout (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    title_uz character varying(255) NOT NULL,
    title_en character varying(255) NOT NULL,
    title_ru character varying(255) NOT NULL,
    description_uz text NOT NULL,
    description_en text NOT NULL,
    description_ru text NOT NULL
);


ALTER TABLE public.mainapp_courseabout OWNER TO maxsud;

--
-- Name: mainapp_courseabout_id_seq; Type: SEQUENCE; Schema: public; Owner: maxsud
--

ALTER TABLE public.mainapp_courseabout ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mainapp_courseabout_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mainapp_coursemodule; Type: TABLE; Schema: public; Owner: maxsud
--

CREATE TABLE public.mainapp_coursemodule (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    title_uz character varying(100) NOT NULL,
    title_en character varying(100) NOT NULL,
    title_ru character varying(100) NOT NULL,
    course_id bigint NOT NULL
);


ALTER TABLE public.mainapp_coursemodule OWNER TO maxsud;

--
-- Name: mainapp_coursemodule_id_seq; Type: SEQUENCE; Schema: public; Owner: maxsud
--

ALTER TABLE public.mainapp_coursemodule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mainapp_coursemodule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mainapp_educationabout; Type: TABLE; Schema: public; Owner: maxsud
--

CREATE TABLE public.mainapp_educationabout (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    icon character varying(100) NOT NULL,
    title_uz character varying(255) NOT NULL,
    title_en character varying(255) NOT NULL,
    title_ru character varying(255) NOT NULL,
    description_uz text NOT NULL,
    description_en text NOT NULL,
    description_ru text NOT NULL
);


ALTER TABLE public.mainapp_educationabout OWNER TO maxsud;

--
-- Name: mainapp_educationabout_id_seq; Type: SEQUENCE; Schema: public; Owner: maxsud
--

ALTER TABLE public.mainapp_educationabout ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mainapp_educationabout_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mainapp_moduletheme; Type: TABLE; Schema: public; Owner: maxsud
--

CREATE TABLE public.mainapp_moduletheme (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    title_uz character varying(100) NOT NULL,
    title_en character varying(100) NOT NULL,
    title_ru character varying(100) NOT NULL,
    module_id bigint NOT NULL
);


ALTER TABLE public.mainapp_moduletheme OWNER TO maxsud;

--
-- Name: mainapp_moduletheme_id_seq; Type: SEQUENCE; Schema: public; Owner: maxsud
--

ALTER TABLE public.mainapp_moduletheme ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mainapp_moduletheme_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mainapp_news; Type: TABLE; Schema: public; Owner: maxsud
--

CREATE TABLE public.mainapp_news (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    title_uz character varying(255) NOT NULL,
    title_en character varying(255) NOT NULL,
    title_ru character varying(255) NOT NULL,
    description_uz text NOT NULL,
    description_en text NOT NULL,
    description_ru text NOT NULL,
    banner character varying(100) NOT NULL,
    status_id bigint,
    link character varying(500)
);


ALTER TABLE public.mainapp_news OWNER TO maxsud;

--
-- Name: mainapp_news_id_seq; Type: SEQUENCE; Schema: public; Owner: maxsud
--

ALTER TABLE public.mainapp_news ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mainapp_news_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mainapp_statistics; Type: TABLE; Schema: public; Owner: maxsud
--

CREATE TABLE public.mainapp_statistics (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    total_students integer NOT NULL,
    total_graduates integer NOT NULL,
    total_employed integer NOT NULL,
    avg_duration double precision NOT NULL,
    avg_start_salary double precision NOT NULL,
    partners integer NOT NULL,
    CONSTRAINT mainapp_statistics_partners_check CHECK ((partners >= 0)),
    CONSTRAINT mainapp_statistics_total_employed_check CHECK ((total_employed >= 0)),
    CONSTRAINT mainapp_statistics_total_graduates_check CHECK ((total_graduates >= 0)),
    CONSTRAINT mainapp_statistics_total_students_check CHECK ((total_students >= 0))
);


ALTER TABLE public.mainapp_statistics OWNER TO maxsud;

--
-- Name: mainapp_statistics_id_seq; Type: SEQUENCE; Schema: public; Owner: maxsud
--

ALTER TABLE public.mainapp_statistics ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mainapp_statistics_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mainapp_status; Type: TABLE; Schema: public; Owner: maxsud
--

CREATE TABLE public.mainapp_status (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    name_uz character varying(100) NOT NULL,
    name_en character varying(100) NOT NULL,
    name_ru character varying(100) NOT NULL
);


ALTER TABLE public.mainapp_status OWNER TO maxsud;

--
-- Name: mainapp_status_id_seq; Type: SEQUENCE; Schema: public; Owner: maxsud
--

ALTER TABLE public.mainapp_status ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mainapp_status_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mainapp_teacher; Type: TABLE; Schema: public; Owner: maxsud
--

CREATE TABLE public.mainapp_teacher (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    full_name character varying(255) NOT NULL,
    bio_uz text,
    bio_en text,
    bio_ru text,
    profession character varying(25) NOT NULL,
    experience integer NOT NULL,
    company character varying(25),
    total_students integer,
    total_projects integer,
    photo character varying(100) NOT NULL,
    github_link character varying(200),
    linkedin_link character varying(200),
    twitter_link character varying(200),
    CONSTRAINT mainapp_teacher_experience_check CHECK ((experience >= 0)),
    CONSTRAINT mainapp_teacher_total_projects_check CHECK ((total_projects >= 0)),
    CONSTRAINT mainapp_teacher_total_students_check CHECK ((total_students >= 0))
);


ALTER TABLE public.mainapp_teacher OWNER TO maxsud;

--
-- Name: mainapp_teacher_id_seq; Type: SEQUENCE; Schema: public; Owner: maxsud
--

ALTER TABLE public.mainapp_teacher ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mainapp_teacher_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mainapp_teacherachievement; Type: TABLE; Schema: public; Owner: maxsud
--

CREATE TABLE public.mainapp_teacherachievement (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    title_uz character varying(255) NOT NULL,
    title_en character varying(255) NOT NULL,
    title_ru character varying(255) NOT NULL,
    teacher_id bigint NOT NULL
);


ALTER TABLE public.mainapp_teacherachievement OWNER TO maxsud;

--
-- Name: mainapp_teacherachievement_id_seq; Type: SEQUENCE; Schema: public; Owner: maxsud
--

ALTER TABLE public.mainapp_teacherachievement ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mainapp_teacherachievement_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mainapp_teacherskill; Type: TABLE; Schema: public; Owner: maxsud
--

CREATE TABLE public.mainapp_teacherskill (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    name_uz character varying(100) NOT NULL,
    name_en character varying(100) NOT NULL,
    name_ru character varying(100) NOT NULL,
    teacher_id bigint NOT NULL
);


ALTER TABLE public.mainapp_teacherskill OWNER TO maxsud;

--
-- Name: mainapp_teacherskill_id_seq; Type: SEQUENCE; Schema: public; Owner: maxsud
--

ALTER TABLE public.mainapp_teacherskill ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mainapp_teacherskill_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mainapp_technology; Type: TABLE; Schema: public; Owner: maxsud
--

CREATE TABLE public.mainapp_technology (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    name_uz character varying(100) NOT NULL,
    name_en character varying(100) NOT NULL,
    name_ru character varying(100) NOT NULL,
    icon character varying(100) NOT NULL,
    course_id bigint NOT NULL
);


ALTER TABLE public.mainapp_technology OWNER TO maxsud;

--
-- Name: mainapp_technology_id_seq; Type: SEQUENCE; Schema: public; Owner: maxsud
--

ALTER TABLE public.mainapp_technology ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mainapp_technology_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: maxsud
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: maxsud
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: maxsud
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add company	7	add_company
26	Can change company	7	change_company
27	Can delete company	7	delete_company
28	Can view company	7	view_company
29	Can add course	8	add_course
30	Can change course	8	change_course
31	Can delete course	8	delete_course
32	Can view course	8	view_course
33	Can add course about	9	add_courseabout
34	Can change course about	9	change_courseabout
35	Can delete course about	9	delete_courseabout
36	Can view course about	9	view_courseabout
37	Can add education about	10	add_educationabout
38	Can change education about	10	change_educationabout
39	Can delete education about	10	delete_educationabout
40	Can view education about	10	view_educationabout
41	Can add statistics	11	add_statistics
42	Can change statistics	11	change_statistics
43	Can delete statistics	11	delete_statistics
44	Can view statistics	11	view_statistics
45	Can add status	12	add_status
46	Can change status	12	change_status
47	Can delete status	12	delete_status
48	Can view status	12	view_status
49	Can add teacher	13	add_teacher
50	Can change teacher	13	change_teacher
51	Can delete teacher	13	delete_teacher
52	Can view teacher	13	view_teacher
53	Can add contact message	14	add_contactmessage
54	Can change contact message	14	change_contactmessage
55	Can delete contact message	14	delete_contactmessage
56	Can view contact message	14	view_contactmessage
57	Can add course module	15	add_coursemodule
58	Can change course module	15	change_coursemodule
59	Can delete course module	15	delete_coursemodule
60	Can view course module	15	view_coursemodule
61	Can add module theme	16	add_moduletheme
62	Can change module theme	16	change_moduletheme
63	Can delete module theme	16	delete_moduletheme
64	Can view module theme	16	view_moduletheme
65	Can add news	17	add_news
66	Can change news	17	change_news
67	Can delete news	17	delete_news
68	Can view news	17	view_news
69	Can add teacher achievement	18	add_teacherachievement
70	Can change teacher achievement	18	change_teacherachievement
71	Can delete teacher achievement	18	delete_teacherachievement
72	Can view teacher achievement	18	view_teacherachievement
73	Can add teacher skill	19	add_teacherskill
74	Can change teacher skill	19	change_teacherskill
75	Can delete teacher skill	19	delete_teacherskill
76	Can view teacher skill	19	view_teacherskill
77	Can add technology	20	add_technology
78	Can change technology	20	change_technology
79	Can delete technology	20	delete_technology
80	Can view technology	20	view_technology
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: maxsud
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
1	pbkdf2_sha256$1000000$VgzVRvVTeI32bpYPgaKiu0$LP6WvGqiO9ZKzJasYF2NzQRiYBiC3rJfEA5RWiffB2A=	\N	t	admin				t	t	2026-01-04 16:19:22.162761+00
2	pbkdf2_sha256$1000000$z9iPaL0P1LcHvX2V0vQwuy$leDK98RnQ1uGdbljCbcgkR74FSfQGBsl8IHO98TknqQ=	2026-01-08 05:20:06.595593+00	t	iatdhmoiunse				t	t	2026-01-05 04:29:26.710907+00
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: maxsud
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: maxsud
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: maxsud
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2026-01-05 04:31:37.170114+00	1	Statistics object (1)	1	[{"added": {}}]	11	2
2	2026-01-05 05:08:53.162458+00	1	News uz	1	[{"added": {}}]	17	2
3	2026-01-05 05:30:46.879537+00	1	Backend	1	[{"added": {}}]	8	2
4	2026-01-05 05:31:31.173077+00	2	Backend  uz	1	[{"added": {}}]	8	2
5	2026-01-05 05:33:36.59744+00	1	Test	1	[{"added": {}}]	12	2
6	2026-01-05 05:33:58.734485+00	1	4392	1	[{"added": {}}]	7	2
7	2026-01-05 05:35:02.903392+00	2	Statistics object (2)	1	[{"added": {}}]	11	2
8	2026-01-05 05:36:14.535819+00	3	test	1	[{"added": {}}]	8	2
9	2026-01-14 19:13:26.368754+00	2	Nodirbek Kuchkarov	2	[{"changed": {"fields": ["Bio uz", "Bio en", "Bio ru", "Github link", "Linkedin link", "Twitter link"]}}]	13	2
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: maxsud
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	mainapp	company
8	mainapp	course
9	mainapp	courseabout
10	mainapp	educationabout
11	mainapp	statistics
12	mainapp	status
13	mainapp	teacher
14	mainapp	contactmessage
15	mainapp	coursemodule
16	mainapp	moduletheme
17	mainapp	news
18	mainapp	teacherachievement
19	mainapp	teacherskill
20	mainapp	technology
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: maxsud
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-01-04 16:19:03.230982+00
2	auth	0001_initial	2026-01-04 16:19:03.380618+00
3	admin	0001_initial	2026-01-04 16:19:03.421183+00
4	admin	0002_logentry_remove_auto_add	2026-01-04 16:19:03.432712+00
5	admin	0003_logentry_add_action_flag_choices	2026-01-04 16:19:03.445594+00
6	contenttypes	0002_remove_content_type_name	2026-01-04 16:19:03.475303+00
7	auth	0002_alter_permission_name_max_length	2026-01-04 16:19:03.494613+00
8	auth	0003_alter_user_email_max_length	2026-01-04 16:19:03.509545+00
9	auth	0004_alter_user_username_opts	2026-01-04 16:19:03.519199+00
10	auth	0005_alter_user_last_login_null	2026-01-04 16:19:03.532113+00
11	auth	0006_require_contenttypes_0002	2026-01-04 16:19:03.534058+00
12	auth	0007_alter_validators_add_error_messages	2026-01-04 16:19:03.544358+00
13	auth	0008_alter_user_username_max_length	2026-01-04 16:19:03.562904+00
14	auth	0009_alter_user_last_name_max_length	2026-01-04 16:19:03.575078+00
15	auth	0010_alter_group_name_max_length	2026-01-04 16:19:03.587934+00
16	auth	0011_update_proxy_permissions	2026-01-04 16:19:03.599089+00
17	auth	0012_alter_user_first_name_max_length	2026-01-04 16:19:03.608372+00
18	mainapp	0001_initial	2026-01-04 16:19:03.812382+00
19	sessions	0001_initial	2026-01-04 16:19:03.834621+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: maxsud
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
g9doqcejbn4gq260txwqs9jzm1ena987	.eJxVjEEOwiAQRe_C2hA6UGBcuvcMZGAGWzVtUtqV8e7apAvd_vfef6lE2zqkrcmSRlZnBer0u2UqD5l2wHeabrMu87QuY9a7og_a9HVmeV4O9-9goDZ86xrJ9wHIG-w7WzgiSKxoulqc41wCBXQdsEGfxaGIAVvZWxsBQvFWvT_V_TdV:1vccE0:Ww6ImyCuEeRqdPQUkCLxUvicTn3-cl5eYfpx-davWQM	2026-01-19 04:29:48.763899+00
ypznfj8al617o1lqad8y5y64mjsh9t4a	.eJxVjEEOwiAQRe_C2hA6UGBcuvcMZGAGWzVtUtqV8e7apAvd_vfef6lE2zqkrcmSRlZnBer0u2UqD5l2wHeabrMu87QuY9a7og_a9HVmeV4O9-9goDZ86xrJ9wHIG-w7WzgiSKxoulqc41wCBXQdsEGfxaGIAVvZWxsBQvFWvT_V_TdV:1vccEb:ILx5c3a8TygqDznN_KSFjPb7xCdJNJZvdkXx6lVTqo8	2026-01-19 04:30:25.092718+00
s7rpzksb863q370eeobihqhrelyjg6s3	.eJxVjEEOwiAQRe_C2hA6UGBcuvcMZGAGWzVtUtqV8e7apAvd_vfef6lE2zqkrcmSRlZnBer0u2UqD5l2wHeabrMu87QuY9a7og_a9HVmeV4O9-9goDZ86xrJ9wHIG-w7WzgiSKxoulqc41wCBXQdsEGfxaGIAVvZWxsBQvFWvT_V_TdV:1vdiRK:71XaEKgjLla7PlAB0kh1jnWB1nMOffqenSkE0-tIV78	2026-01-22 05:20:06.609497+00
\.


--
-- Data for Name: mainapp_company; Type: TABLE DATA; Schema: public; Owner: maxsud
--

COPY public.mainapp_company (id, created_at, updated_at, logo, workers) FROM stdin;
1	2026-01-05 05:33:58.727662+00	2026-01-05 05:33:58.727687+00	company_logos/logo.jpg	4392
\.


--
-- Data for Name: mainapp_contactmessage; Type: TABLE DATA; Schema: public; Owner: maxsud
--

COPY public.mainapp_contactmessage (id, name, phone_number, created_at, course_id) FROM stdin;
\.


--
-- Data for Name: mainapp_course; Type: TABLE DATA; Schema: public; Owner: maxsud
--

COPY public.mainapp_course (id, created_at, updated_at, banner, title_uz, title_en, title_ru, description_uz, description_en, description_ru, price, duration, students) FROM stdin;
7	2026-01-06 08:14:13.965391+00	2026-01-06 08:14:13.96542+00	course_banners/4.png	SMM	SMM	SMM	SMM mutaxassislari brendlarni ijtimoiy tarmoqlarda targ‘ib qiladi: kontent, auditoriya va reklama bilan ishlaydi, va shu orqali daromad qiladi.	SMM	SMM	1800000.00	3	0
8	2026-01-06 08:18:55.24022+00	2026-01-06 08:18:55.240247+00	course_banners/5.png	Foundation	Foundation	Foundation	0dan kompyuterdan professionallardek foydalanishni o'rganing!	Foundation	Foundation	1200000.00	2	500
9	2026-01-06 08:27:34.163566+00	2026-01-06 08:27:34.163811+00	course_banners/Дизайн_без_названия_25.png	Interyer Dizayn	Interyer Dizayn	Interyer Dizayn	Xonadon va "участка"larni ichki qismini dizayn qiling va har bir m2 uchun daromad qiling!	Interyer Dizayn	Interyer Dizayn	1400000.00	6	110
5	2026-01-06 08:11:01.062763+00	2026-01-06 12:59:05.853051+00	course_banners/2_5RBSdy6.png	Backend-dasturlash	Backend-dasturlash	Backend-dasturlash	Backend-dasturchi programmaning ichki qismi bilan ishlaydi va tizim to'g'ri faoliyat yuritishini mas'ul mutaxassis hisoblanadi.	Backend-dasturlash	Backend-dasturlash	1400000.00	5	260
6	2026-01-06 08:12:42.956222+00	2026-01-06 13:01:35.551935+00	course_banners/3_Oqr7VSm.png	Kiberxavfsizlik	Cybersecurity	Kiberxavfsizlik	12 oy ichida talab yuqori bo‘lgan IT kasbini egallang, tizimlardagi zaifliklarni aniqlash va ma’lumotlarni himoya qilishni o‘rganing!	Kiberxavfsizlik	Kiberxavfsizlik	1300000.00	12	420
4	2026-01-06 06:12:56.430156+00	2026-01-15 11:25:45.10956+00	course_banners/Foundation_banner.png	Frontend-dasturlash	Frontend-development	Frontend-разработка	Frontend-dasturchilar saytlar, dasturlar va ilovalarning tashqi qismi bilan ishlaydi. Hamma narsa to‘g‘ri ko‘rsatilishi va ishlashini aynan frontend-dasturchilar nazorat qiladi.	frontend	frontend	1400000.00	7	280
\.


--
-- Data for Name: mainapp_courseabout; Type: TABLE DATA; Schema: public; Owner: maxsud
--

COPY public.mainapp_courseabout (id, created_at, updated_at, title_uz, title_en, title_ru, description_uz, description_en, description_ru) FROM stdin;
1	2026-01-08 04:59:28.509134+00	2026-01-08 04:59:28.509234+00	Talabalar	Talabalar	Talabalar	O'z kelajagini IT bilan bog'lamoqchi bo'lgan talabalar bizning kurslarimizda o'qishlari mumkin	O'z kelajagini IT bilan bog'lamoqchi bo'lgan talabalar bizning kurslarimizda o'qishlari mumkin	O'z kelajagini IT bilan bog'lamoqchi bo'lgan talabalar bizning kurslarimizda o'qishlari mumkin
2	2026-01-08 05:01:05.015926+00	2026-01-08 05:01:05.015954+00	Xodimlar	Xodimlar	Xodimlar	Kechki vaqt o'zingizga qulay payt IT'ni o'rganishingiz mumkin	Kechki vaqt o'zingizga qulay payt IT'ni o'rganishingiz mumkin	Kechki vaqt o'zingizga qulay payt IT'ni o'rganishingiz mumkin
3	2026-01-08 05:01:23.6047+00	2026-01-08 05:01:23.604726+00	Kasbini o'zgartirmoqchilar	Kasbini o'zgartirmoqchilar	Kasbini o'zgartirmoqchilar	Hozirgi kasbidan qoniqmayotganlar o'z kasbini o'zgartirishlari mumkin	Hozirgi kasbidan qoniqmayotganlar o'z kasbini o'zgartirishlari mumkin	Hozirgi kasbidan qoniqmayotganlar o'z kasbini o'zgartirishlari mumkin
4	2026-01-08 05:01:48.423732+00	2026-01-08 05:01:48.423775+00	Maktab o'quvchilari	Maktab o'quvchilari	Maktab o'quvchilari	Yoshlikdan IT'ni o'rganib, kelajagini hozirdan qurishlari mumkin	Yoshlikdan IT'ni o'rganib, kelajagini hozirdan qurishlari mumkin	Yoshlikdan IT'ni o'rganib, kelajagini hozirdan qurishlari mumkin
\.


--
-- Data for Name: mainapp_coursemodule; Type: TABLE DATA; Schema: public; Owner: maxsud
--

COPY public.mainapp_coursemodule (id, created_at, updated_at, title_uz, title_en, title_ru, course_id) FROM stdin;
2	2026-01-06 11:00:37.818453+00	2026-01-06 11:00:37.818474+00	2-modul: Advanced CSS & UI	2-modul: Advanced CSS & UI	2-modul: Advanced CSS & UI	4
3	2026-01-06 11:01:28.932635+00	2026-01-06 11:01:28.932664+00	3-modul: JavaScript Fundamentals	3-modul: JavaScript Fundamentals	3-modul: JavaScript Fundamentals	4
1	2026-01-06 10:59:37.680763+00	2026-01-06 11:01:39.79062+00	1-modul: HTML & CSS	1-modul: HTML & CSS	1-modul: HTML & CSS	4
4	2026-01-06 11:04:24.249084+00	2026-01-06 11:05:19.645668+00	4-modul: Advanced JavaScript + TypeScript	4-modul: Advanced JavaScript + TypeScript	4-modul: Advanced JavaScript + TypeScript	4
5	2026-01-06 11:04:50.020888+00	2026-01-06 11:05:41.786117+00	5-modul: Vue.js	5-modul: Vue.js	5-modul: Vue.js	4
6	2026-01-06 11:09:13.252121+00	2026-01-06 11:09:13.2522+00	6-modul: Nuxt.js	6-modul: Nuxt.js	6-modul: Nuxt.js	4
7	2026-01-06 12:55:45.338315+00	2026-01-06 12:55:45.338388+00	1. Python asoslari va chuqur bilimlari	1. Python asoslari va chuqur bilimlari	1. Python asoslari va chuqur bilimlari	5
8	2026-01-06 12:56:07.016419+00	2026-01-06 12:56:07.016443+00	2. OOP (Ob'ektga yo‘naltirilgan dasturlash) – chuqur	2. OOP (Ob'ektga yo‘naltirilgan dasturlash) – chuqur	2. OOP (Ob'ektga yo‘naltirilgan dasturlash) – chuqur	5
9	2026-01-06 12:56:28.772379+00	2026-01-06 12:56:28.7724+00	3. Ma’lumotlar bazasi bilan ishlash	3. Ma’lumotlar bazasi bilan ishlash	3. Ma’lumotlar bazasi bilan ishlash	5
10	2026-01-06 12:57:03.902264+00	2026-01-06 12:57:03.902298+00	4. Django framework – asosiy qism	4. Django framework – asosiy qism	4. Django framework – asosiy qism	5
11	2026-01-06 12:57:34.118735+00	2026-01-06 12:57:34.118763+00	5. Foydalanuvchilar bilan ishlash	5. Foydalanuvchilar bilan ishlash	5. Foydalanuvchilar bilan ishlash	5
12	2026-01-06 12:57:53.687239+00	2026-01-06 12:57:53.68726+00	6. Django REST Framework (DRF)	6. Django REST Framework (DRF)	6. Django REST Framework (DRF)	5
13	2026-01-06 13:05:41.093784+00	2026-01-06 13:05:41.093817+00	7. Telegram Bot yaratish (Aiogram 3.x)	7. Telegram Bot yaratish (Aiogram 3.x)	7. Telegram Bot yaratish (Aiogram 3.x)	5
14	2026-01-06 13:06:11.130226+00	2026-01-06 13:06:11.130254+00	8. Celery va Celery Beat	8. Celery va Celery Beat	8. Celery va Celery Beat	5
15	2026-01-06 13:06:39.079723+00	2026-01-06 13:06:39.079746+00	9. Real-time aloqa	9. Real-time aloqa	9. Real-time aloqa	5
16	2026-01-06 13:20:13.905837+00	2026-01-06 13:20:13.905888+00	10. Server va Deploy	10. Server va Deploy	10. Server va Deploy	5
\.


--
-- Data for Name: mainapp_educationabout; Type: TABLE DATA; Schema: public; Owner: maxsud
--

COPY public.mainapp_educationabout (id, created_at, updated_at, icon, title_uz, title_en, title_ru, description_uz, description_en, description_ru) FROM stdin;
1	2026-01-08 05:05:11.216276+00	2026-01-08 05:05:11.216307+00	education_about_icons/monitor.png	Kompyuter bilan ta'minlaymiz	Kompyuter bilan ta'minlaymiz	Kompyuter bilan ta'minlaymiz	Noutbuki yo'q o'quvchilarni o'quv jarayonida o'zimiz kompyuter bilan ta'minlaymiz	Noutbuki yo'q o'quvchilarni o'quv jarayonida o'zimiz kompyuter bilan ta'minlaymiz	Noutbuki yo'q o'quvchilarni o'quv jarayonida o'zimiz kompyuter bilan ta'minlaymiz
2	2026-01-08 05:08:20.542923+00	2026-01-08 05:08:20.542947+00	education_about_icons/pencil.png	Darslarimiz barchasi 70% amaliyotdan iborat iborat	Darslarimiz barchasi 70% amaliyotdan iborat iborat	Darslarimiz barchasi 70% amaliyotdan iborat iborat	Biz faqatgina nazariy bilim bilan cheklanmaymiz, chunki o'quvchi bozorda talabgir kadr bo'lib chiqishi biz uchun muhim	Biz faqatgina nazariy bilim bilan cheklanmaymiz, chunki o'quvchi bozorda talabgir kadr bo'lib chiqishi biz uchun muhim	Biz faqatgina nazariy bilim bilan cheklanmaymiz, chunki o'quvchi bozorda talabgir kadr bo'lib chiqishi biz uchun muhim
3	2026-01-08 05:09:42.997909+00	2026-01-08 05:09:42.997939+00	education_about_icons/briefcase.png	Real loyihalar bilan ishlaysiz va kurs ohirida tayyor portfolio bilan chiqasiz	Real loyihalar bilan ishlaysiz va kurs ohirida tayyor portfolio bilan chiqasiz	Real loyihalar bilan ishlaysiz va kurs ohirida tayyor portfolio bilan chiqasiz	Real loyihalar asosida amaliyot qildirganimiz sababli, o'quvchilarimiz kursni ohiriga tayyor portfolio bilan chiqishadi	Real loyihalar asosida amaliyot qildirganimiz sababli, o'quvchilarimiz kursni ohiriga tayyor portfolio bilan chiqishadi	Real loyihalar asosida amaliyot qildirganimiz sababli, o'quvchilarimiz kursni ohiriga tayyor portfolio bilan chiqishadi
4	2026-01-08 05:11:10.334888+00	2026-01-08 05:11:10.334927+00	education_about_icons/technical-support.png	Doimiy qo'llab-quvvatlash	Doimiy qo'llab-quvvatlash	Doimiy qo'llab-quvvatlash	Agarda darsda ubu nimani tushunmasangiz, yoki ma'lum bir sabablarga ko'rsa darsni o'kazib yuborsangiz, xavotirlanmang, ustozlarimiz doimo har bir o'quvchiga individual yondashuv qilishga tayyor	Agarda darsda ubu nimani tushunmasangiz, yoki ma'lum bir sabablarga ko'rsa darsni o'kazib yuborsangiz, xavotirlanmang, ustozlarimiz doimo har bir o'quvchiga individual yondashuv qilishga tayyor	Agarda darsda ubu nimani tushunmasangiz, yoki ma'lum bir sabablarga ko'rsa darsni o'kazib yuborsangiz, xavotirlanmang, ustozlarimiz doimo har bir o'quvchiga individual yondashuv qilishga tayyor
5	2026-01-08 05:12:29.322425+00	2026-01-08 05:12:29.322451+00	education_about_icons/self-improvement.png	Soft Skillar	Soft Skillar	Soft Skillar	Kurslarimizda o'qib siz nafaqat texnik bilimlarni, balki jamoa bilan to'g'ri ishlash, muammolarga tezkor yechim topa olish va bundan keyin ham mustaqil bilim olishi ko'nikmalarni ham rivojlantirasiz.	Kurslarimizda o'qib siz nafaqat texnik bilimlarni, balki jamoa bilan to'g'ri ishlash, muammolarga tezkor yechim topa olish va bundan keyin ham mustaqil bilim olishi ko'nikmalarni ham rivojlantirasiz.	Kurslarimizda o'qib siz nafaqat texnik bilimlarni, balki jamoa bilan to'g'ri ishlash, muammolarga tezkor yechim topa olish va bundan keyin ham mustaqil bilim olishi ko'nikmalarni ham rivojlantirasiz.
6	2026-01-08 05:13:29.65188+00	2026-01-08 05:13:29.651903+00	education_about_icons/service.png	Ish bilan ta'minlashda ko'mak	Ish bilan ta'minlashda ko'mak	Ish bilan ta'minlashda ko'mak	Kursni muvaffaqiyatli tamomlagan o'quvchilarni albatta ish topishiga ko'maklashamiz	Kursni muvaffaqiyatli tamomlagan o'quvchilarni albatta ish topishiga ko'maklashamiz	Kursni muvaffaqiyatli tamomlagan o'quvchilarni albatta ish topishiga ko'maklashamiz
\.


--
-- Data for Name: mainapp_moduletheme; Type: TABLE DATA; Schema: public; Owner: maxsud
--

COPY public.mainapp_moduletheme (id, created_at, updated_at, title_uz, title_en, title_ru, module_id) FROM stdin;
1	2026-01-06 11:02:07.310087+00	2026-01-06 11:02:07.31011+00	HTML kirish, teglarga kirish	HTML kirish, teglarga kirish	HTML kirish, teglarga kirish	1
2	2026-01-06 11:11:18.877608+00	2026-01-06 11:11:18.877633+00	HTML struktura	HTML struktura	HTML struktura	1
3	2026-01-06 11:11:57.581466+00	2026-01-06 11:11:57.581492+00	Semantik HTML	Semantik HTML	Semantik HTML	1
4	2026-01-06 11:12:20.429728+00	2026-01-06 11:12:20.42975+00	CSS asoslari	CSS asoslari	CSS asoslari	1
5	2026-01-06 11:12:37.408266+00	2026-01-06 11:12:37.408292+00	Selectorlar	Selectorlar	Selectorlar	1
6	2026-01-06 11:12:56.93657+00	2026-01-06 11:12:56.936595+00	Box model	Box model	Box model	1
7	2026-01-06 11:13:13.77432+00	2026-01-06 11:13:47.659744+00	Flexbox	Flexbox	Flexbox	1
8	2026-01-06 11:16:32.444556+00	2026-01-06 11:16:32.444579+00	Grid	Grid	Grid	1
9	2026-01-06 11:17:21.58448+00	2026-01-06 11:17:21.584506+00	CSS Reset & Normalize	CSS Reset & Normalize	CSS Reset & Normalize	1
10	2026-01-06 11:18:26.950698+00	2026-01-06 11:18:26.950722+00	Responsiv dizayn	Responsiv dizayn	Responsiv dizayn	1
11	2026-01-06 11:31:52.883939+00	2026-01-06 11:31:52.883974+00	Media queries	Media queries	Media queries	1
12	2026-01-06 11:32:51.199283+00	2026-01-06 11:32:51.199332+00	Mini loyiha (Landing page)	Mini loyiha (Landing page)	Mini loyiha (Landing page)	1
13	2026-01-06 11:33:33.659976+00	2026-01-06 11:33:33.660033+00	SCSS asoslari	SCSS asoslari	SCSS asoslari	2
14	2026-01-06 11:34:04.498839+00	2026-01-06 11:34:04.498868+00	Nesting & Variables	Nesting & Variables	Nesting & Variables	2
15	2026-01-06 11:34:30.331472+00	2026-01-06 11:34:30.331493+00	Mixins	Mixins	Mixins	2
16	2026-01-06 11:34:51.734543+00	2026-01-06 11:34:51.734564+00	BEM metodologiyasi	BEM metodologiyasi	BEM metodologiyasi	2
17	2026-01-06 11:35:18.597363+00	2026-01-06 11:35:18.597388+00	Transition & Animations	Transition & Animations	Transition & Animations	2
18	2026-01-06 11:35:42.185004+00	2026-01-06 11:35:42.185027+00	Transformlar	Transformlar	Transformlar	2
19	2026-01-06 11:36:02.329812+00	2026-01-06 11:36:02.329833+00	UI prinsiplar	UI prinsiplar	UI prinsiplar	2
20	2026-01-06 11:36:22.77398+00	2026-01-06 11:36:22.774032+00	Figma’dan HTML/CSS	Figma’dan HTML/CSS	Figma’dan HTML/CSS	2
21	2026-01-06 11:36:41.764693+00	2026-01-06 11:36:41.764719+00	Dark/Light mod	Dark/Light mod	Dark/Light mod	2
22	2026-01-06 11:36:58.248122+00	2026-01-06 11:36:58.248148+00	Tailwind intro	Tailwind intro	Tailwind intro	2
23	2026-01-06 11:37:24.062193+00	2026-01-06 11:37:24.062213+00	Component-based UI	Component-based UI	Component-based UI	2
24	2026-01-06 11:37:53.655208+00	2026-01-06 11:37:53.655232+00	Mini UI Kit loyihasi	Mini UI Kit loyihasi Mini UI Kit loyihasi	Mini UI Kit loyihasi	2
25	2026-01-06 11:38:19.763372+00	2026-01-06 11:38:19.7634+00	JS kirish	JS kirish	JS kirish	3
26	2026-01-06 11:38:49.934947+00	2026-01-06 11:38:49.93497+00	Variables	Variables	Variables	3
27	2026-01-06 11:39:11.910521+00	2026-01-06 11:39:11.910547+00	Data types	Data types	Data types	3
28	2026-01-06 11:39:32.447806+00	2026-01-06 11:39:32.447824+00	Conditions	Conditions	Conditions	3
29	2026-01-06 11:39:59.00053+00	2026-01-06 11:39:59.000555+00	Loops	LoopsLoops	Loops	3
30	2026-01-06 11:40:19.035336+00	2026-01-06 11:40:19.035357+00	Functions	Functions	Functions	3
31	2026-01-06 11:41:14.365545+00	2026-01-06 11:41:14.365572+00	Arrays	Arrays	Arrays	3
32	2026-01-06 11:41:31.801838+00	2026-01-06 11:41:31.801858+00	Objects	Objects	Objects	3
33	2026-01-06 11:41:52.124777+00	2026-01-06 11:41:52.124813+00	DOM manipulyatsiya	DOM manipulyatsiya	DOM manipulyatsiya	3
34	2026-01-06 11:42:12.128146+00	2026-01-06 11:42:12.128167+00	Events	Events	Events	3
35	2026-01-06 11:42:35.521212+00	2026-01-06 11:42:35.521234+00	Fetch API kirish	Fetch API kirish	Fetch API kirish	3
36	2026-01-06 11:49:09.153801+00	2026-01-06 11:49:09.15383+00	Mini JS loyihaMini JS loyiha	Mini JS loyiha	Mini JS loyiha	3
37	2026-01-06 11:49:58.08501+00	2026-01-06 11:49:58.085039+00	ES6+, let/const	ES6+, let/constES6+, let/const	ES6+, let/const	4
38	2026-01-06 11:50:23.682961+00	2026-01-06 11:50:23.683018+00	Arrow functions	Arrow functions	Arrow functions	4
39	2026-01-06 11:50:44.246789+00	2026-01-06 11:50:44.246818+00	Spread & Rest	Spread & Rest	Spread & Rest	4
40	2026-01-06 11:51:07.975446+00	2026-01-06 11:51:07.975514+00	Async/Await	Async/AwaitAsync/Await	Async/Await	4
41	2026-01-06 11:51:49.357591+00	2026-01-06 11:51:49.357629+00	Promises	Promises	Promises	4
42	2026-01-06 11:52:11.379322+00	2026-01-06 11:52:11.379358+00	Modular JS	Modular JS	Modular JS	4
43	2026-01-06 11:52:34.781261+00	2026-01-06 11:52:49.067475+00	API bilan ishlash	API bilan ishlash	API bilan ishlash	4
44	2026-01-06 12:06:54.44071+00	2026-01-06 12:06:54.440733+00	Error handling	Error handlingError handling	Error handling	4
45	2026-01-06 12:07:19.964783+00	2026-01-06 12:07:19.964818+00	TypeScript kirish	TypeScript kirish	TypeScript kirish	4
46	2026-01-06 12:07:40.237499+00	2026-01-06 12:07:40.237521+00	Types	Types	Types	4
47	2026-01-06 12:08:02.228819+00	2026-01-06 12:08:02.228846+00	Interfaces & Classes	Interfaces & Classes	Interfaces & Classes	4
48	2026-01-06 12:08:30.811439+00	2026-01-06 12:08:53.607735+00	TS mini loyiha	TS mini loyiha	TS mini loyiha	4
49	2026-01-06 12:12:50.523935+00	2026-01-06 12:12:50.523958+00	Vue asoslari	Vue asoslari	Vue asoslari	5
50	2026-01-06 12:13:14.316474+00	2026-01-06 12:13:14.316499+00	Componentlar	Componentlar	Componentlar	5
51	2026-01-06 12:13:40.621552+00	2026-01-06 12:13:40.621573+00	Props	Props	Props	5
52	2026-01-06 12:14:15.315743+00	2026-01-06 12:14:54.930622+00	Emits	Emits	Emits	5
53	2026-01-06 12:15:45.88481+00	2026-01-06 12:15:45.884836+00	Computed & Watch	Computed & Watch	Computed & Watch	5
54	2026-01-06 12:16:06.021162+00	2026-01-06 12:16:06.02119+00	Lifecycle hooks	Lifecycle hooks	Lifecycle hooks	5
55	2026-01-06 12:16:26.237596+00	2026-01-06 12:16:26.237626+00	Vue Router kirish	Vue Router kirish	Vue Router kirish	5
56	2026-01-06 12:16:55.837622+00	2026-01-06 12:16:55.837651+00	Dinamik routelar	Dinamik routelar	Dinamik routelar	5
57	2026-01-06 12:17:15.16694+00	2026-01-06 12:17:15.166971+00	Pinia/Vuex	Pinia/Vuex	Pinia/Vuex	5
58	2026-01-06 12:17:35.605557+00	2026-01-06 12:17:35.605591+00	API bilan Vue’da ishlash	API bilan Vue’da ishlashAPI bilan Vue’da ishlash	API bilan Vue’da ishlash	5
59	2026-01-06 12:18:01.38385+00	2026-01-06 12:18:01.383879+00	Real loyiha	Real loyiha	Real loyiha	5
60	2026-01-06 12:18:50.85269+00	2026-01-06 12:18:50.852716+00	Vue mini dashboard	Vue mini dashboard	Vue mini dashboard	5
61	2026-01-06 12:19:18.531595+00	2026-01-06 12:19:18.531639+00	Nuxt kirish	Nuxt kirish	Nuxt kirish	6
62	2026-01-06 12:19:49.206034+00	2026-01-06 12:19:49.206083+00	File-based routing	File-based routing	File-based routing	6
63	2026-01-06 12:20:11.429258+00	2026-01-06 12:20:11.429286+00	Layouts	Layouts	Layouts	6
64	2026-01-06 12:20:27.27705+00	2026-01-06 12:20:27.27708+00	Pages	Pages	Pages	6
65	2026-01-06 12:20:47.169133+00	2026-01-06 12:20:47.169155+00	Components	Components	Components	6
66	2026-01-06 12:21:06.080307+00	2026-01-06 12:21:06.080336+00	Server functions	Server functions	Server functions	6
67	2026-01-06 12:21:25.504776+00	2026-01-06 12:21:25.5048+00	Middleware	Middleware	Middleware	6
68	2026-01-06 12:21:43.856929+00	2026-01-06 12:21:43.856957+00	SEO & Meta	SEO & Meta	SEO & Meta	6
69	2026-01-06 12:22:02.380938+00	2026-01-06 12:22:02.380965+00	Auth	Auth	Auth	6
70	2026-01-06 12:22:24.545129+00	2026-01-06 12:22:24.545151+00	API routes	API routes	API routes	6
71	2026-01-06 12:22:42.973869+00	2026-01-06 12:22:42.97389+00	Deployment	Deployment	Deployment	6
72	2026-01-06 12:23:32.254206+00	2026-01-06 12:23:32.254228+00	Nuxt real loyiha	Nuxt real loyiha	Nuxt real loyiha	6
73	2026-01-06 13:07:14.240768+00	2026-01-06 13:07:14.240796+00	O‘zgaruvchilar, ma’lumot turlari, shart operatorlari, sikllar	O‘zgaruvchilar, ma’lumot turlari, shart operatorlari, sikllar	O‘zgaruvchilar, ma’lumot turlari, shart operatorlari, sikllar	7
74	2026-01-06 13:07:39.9312+00	2026-01-06 13:07:39.931222+00	Funksiyalar, lambda, decoratorlar, generatorlar	Funksiyalar, lambda, decoratorlar, generatorlar	Funksiyalar, lambda, decoratorlar, generatorlar	7
75	2026-01-06 13:07:57.866956+00	2026-01-06 13:07:57.866983+00	Modullar, paketlar, virtual muhit (venv)	Modullar, paketlar, virtual muhit (venv)Modullar, paketlar, virtual muhit (venv)	Modullar, paketlar, virtual muhit (venv)	7
76	2026-01-06 13:10:17.378844+00	2026-01-06 13:10:48.062178+00	Xatoliklarni boshqarish (try-except), logging	Xatoliklarni boshqarish (try-except), logging	Xatoliklarni boshqarish (try-except), logging	7
77	2026-01-06 13:11:25.621177+00	2026-01-06 13:11:25.62122+00	Class va object, init, selfClass va object, init, self	Class va object, init, self	Class va object, init, self	8
78	2026-01-06 13:21:43.989356+00	2026-01-06 13:21:43.989386+00	SQL asoslari (PostgreSQL)	SQL asoslari (PostgreSQL)	SQL asoslari (PostgreSQL)	9
79	2026-01-06 13:22:23.968262+00	2026-01-06 13:22:49.655366+00	Django loyiha tuzilmasi, MVC/MVT	Django loyiha tuzilmasi, MVC/MVTjango loyiha tuzilmasi, MVC/MVT	Django loyiha tuzilmasi, MVC/MVT	10
80	2026-01-06 13:23:09.118843+00	2026-01-06 13:23:09.118868+00	Models, Migrations, Admin panel	Models, Migrations, Admin panel	Models, Migrations, Admin panel	10
81	2026-01-06 13:23:25.83683+00	2026-01-06 13:23:25.836851+00	Views (FBV va CBV), URL routing	Views (FBV va CBV), URL routing	Views (FBV va CBV), URL routing	10
82	2026-01-06 13:23:45.761054+00	2026-01-06 13:23:45.76108+00	Templates, static va media fayllar	Templates, static va media fayllarTemplates, static va media fayllar	Templates, static va media fayllar	10
83	2026-01-06 13:24:06.932612+00	2026-01-06 13:24:06.932637+00	Django ORM chuqur (QuerySet, F(), Q(), annotate, aggregate)	Django ORM chuqur (QuerySet, F(), Q(), annotate, aggregate)	Django ORM chuqur (QuerySet, F(), Q(), annotate, aggregate)	10
84	2026-01-06 13:24:30.832132+00	2026-01-06 13:24:30.832154+00	Django Auth (login, logout, register)	Django Auth (login, logout, register)	Django Auth (login, logout, register)	11
85	2026-01-06 13:25:07.670299+00	2026-01-06 13:25:07.670324+00	Custom User model	Custom User model	Custom User model	11
86	2026-01-06 13:25:26.02731+00	2026-01-06 13:25:26.027337+00	Rol va permissionlar (Groups, custom permissions)	Rol va permissionlar (Groups, custom permissions)	Rol va permissionlar (Groups, custom permissions)	11
88	2026-01-06 13:28:22.212654+00	2026-01-06 13:28:22.212675+00	API nima, REST prinsiplari	API nima, REST prinsiplari	API nima, REST prinsiplari	12
87	2026-01-06 13:25:46.208047+00	2026-01-06 13:29:40.7681+00	Parolni tiklash, email tasdiqlash	Parolni tiklash, email tasdiqlash	Parolni tiklash, email tasdiqlash	11
89	2026-01-06 13:30:09.402229+00	2026-01-06 13:30:09.402255+00	Inkapsulyatsiya, meros olish (inheritance), polimorfizm	Inkapsulyatsiya, meros olish (inheritance), polimorfizm	Inkapsulyatsiya, meros olish (inheritance), polimorfizm	8
90	2026-01-06 13:30:45.349265+00	2026-01-06 13:30:45.349285+00	Property, Staticmethod	Property, Staticmethod	Property, Staticmethod	8
91	2026-01-06 13:31:58.583153+00	2026-01-06 13:31:58.583171+00	Dunder metodlar (str, repr, len va h.k.)	Dunder metodlar (str, repr, len va h.k.)	Dunder metodlar (str, repr, len va h.k.)	8
92	2026-01-06 13:43:12.119636+00	2026-01-06 13:43:12.119681+00	Serializers, ViewSets, Routers	Serializers, ViewSets, Routers	Serializers, ViewSets, Routers	12
93	2026-01-06 13:43:49.662782+00	2026-01-06 13:43:49.662854+00	Authentication (Token, JWT)	Authentication (Token, JWT)	Authentication (Token, JWT)	12
94	2026-01-06 13:44:19.991635+00	2026-01-06 13:44:19.991703+00	Permissions, Throttling, Pagination	Permissions, Throttling, Pagination	Permissions, Throttling, Pagination	12
95	2026-01-06 13:44:44.70505+00	2026-01-06 13:44:44.705077+00	API dokumentatsiyasi (drf-spectacular / swagger)	API dokumentatsiyasi (drf-spectacular / swagger)	API dokumentatsiyasi (drf-spectacular / swagger)	12
96	2026-01-06 13:45:24.960155+00	2026-01-06 13:45:24.96018+00	BotFather bilan bot yaratish	BotFather bilan bot yaratish	BotFather bilan bot yaratish	13
97	2026-01-06 13:45:43.200621+00	2026-01-06 13:45:43.20065+00	Handlerlar, FSM (Finite State Machine)	Handlerlar, FSM (Finite State Machine)	Handlerlar, FSM (Finite State Machine)	13
98	2026-01-06 13:46:08.700689+00	2026-01-06 13:46:08.700718+00	Inline va reply keyboardlar	Inline va reply keyboardlar	Inline va reply keyboardlar	13
99	2026-01-06 13:46:30.721134+00	2026-01-06 13:46:30.721163+00	Webhook va polling	Webhook va polling	Webhook va polling	13
100	2026-01-06 13:46:49.620389+00	2026-01-06 13:46:49.620409+00	Bot + Django admin integratsiyasi	Bot + Django admin integratsiyasi	Bot + Django admin integratsiyasi	13
101	2026-01-06 13:49:04.603156+00	2026-01-06 13:49:04.603181+00	Vazifalarni fonda bajarishVazifalarni fonda bajarish	Vazifalarni fonda bajarish	Vazifalarni fonda bajarish	14
102	2026-01-06 13:49:28.468958+00	2026-01-06 13:49:28.468981+00	Periodic tasks (har kuni hisobot yuborish, eslatmalar)	Periodic tasks (har kuni hisobot yuborish, eslatmalar)	Periodic tasks (har kuni hisobot yuborish, eslatmalar)	14
103	2026-01-06 13:49:47.032012+00	2026-01-06 13:49:47.03204+00	Redis/RabbitMQ broker sifatida	Redis/RabbitMQ broker sifatida	Redis/RabbitMQ broker sifatida	14
104	2026-01-06 13:50:12.492726+00	2026-01-06 13:50:12.492747+00	Django Channels	Django Channels	Django Channels	15
105	2026-01-06 13:54:04.08369+00	2026-01-06 13:54:04.083717+00	WebSocket orqali live chat, bildirishnomalar	WebSocket orqali live chat, bildirishnomalar	WebSocket orqali live chat, bildirishnomalar	15
106	2026-01-06 13:54:29.827907+00	2026-01-06 13:54:29.827933+00	Nginx + Gunicorn	Nginx + Gunicorn	Nginx + Gunicorn	16
107	2026-01-06 13:54:45.896264+00	2026-01-06 13:54:45.896287+00	Docker va Docker Compose	Docker va Docker Compose	Docker va Docker Compose	15
108	2026-01-06 13:55:03.394242+00	2026-01-06 13:55:03.394273+00	Production sozlamalari (DEBUG=False, ALLOWED_HOSTS, environment variables)	Production sozlamalari (DEBUG=False, ALLOWED_HOSTS, environment variables)	Production sozlamalari (DEBUG=False, ALLOWED_HOSTS, environment variables)	16
109	2026-01-06 13:55:19.832843+00	2026-01-06 13:55:19.83287+00	Deploy: Ubuntu serverga (DigitalOcean, Hetzner, VPS)	Deploy: Ubuntu serverga (DigitalOcean, Hetzner, VPS)	Deploy: Ubuntu serverga (DigitalOcean, Hetzner, VPS)	16
\.


--
-- Data for Name: mainapp_news; Type: TABLE DATA; Schema: public; Owner: maxsud
--

COPY public.mainapp_news (id, created_at, updated_at, title_uz, title_en, title_ru, description_uz, description_en, description_ru, banner, status_id, link) FROM stdin;
4	2026-01-10 12:54:46.290478+00	2026-01-10 12:54:46.290533+00	Lorem ipsum dolor sit amet consectetur adipisicing elit.	Lorem ipsum dolor sit amet consectetur adipisicing elit.	Lorem ipsum dolor sit amet consectetur adipisicing elit.	Lorem ipsum dolor sit amet consectetur adipisicing elit.Lorem ipsum dolor sit amet consectetur adipisicing elit.	Lorem ipsum dolor sit amet consectetur adipisicing elit.Lorem ipsum dolor sit amet consectetur adipisicing elit.	Lorem ipsum dolor sit amet consectetur adipisicing elit.Lorem ipsum dolor sit amet consectetur adipisicing elit.	news_banners/e325d85a6686a5f5a482c2c580498089.jpg	\N	
6	2026-01-10 12:56:34.309088+00	2026-01-10 12:56:34.309118+00	Lorem ipsum dolor sit amet consectetur adipisicing elit.	Lorem ipsum dolor sit amet consectetur adipisicing elit.	Lorem ipsum dolor sit amet consectetur adipisicing elit.	Lorem ipsum dolor sit amet consectetur adipisicing elit.Lorem ipsum dolor sit amet consectetur adipisicing elit.	Lorem ipsum dolor sit amet consectetur adipisicing elit.Lorem ipsum dolor sit amet consectetur adipisicing elit.	Lorem ipsum dolor sit amet consectetur adipisicing elit.Lorem ipsum dolor sit amet consectetur adipisicing elit.	news_banners/e325d85a6686a5f5a482c2c580498089_CFzzupK.jpg	1	
7	2026-01-10 12:57:23.328575+00	2026-01-10 12:57:23.328607+00	Lorem ipsum dolor sit amet consectetur adipisicing elit.	Lorem ipsum dolor sit amet consectetur adipisicing elit.	Lorem ipsum dolor sit amet consectetur adipisicing elit.	Lorem ipsum dolor sit amet consectetur adipisicing elit.Lorem ipsum dolor sit amet consectetur adipisicing elit.	Lorem ipsum dolor sit amet consectetur adipisicing elit.Lorem ipsum dolor sit amet consectetur adipisicing elit.	Lorem ipsum dolor sit amet consectetur adipisicing elit.Lorem ipsum dolor sit amet consectetur adipisicing elit.	news_banners/e325d85a6686a5f5a482c2c580498089_TCBd7Ia.jpg	1	
\.


--
-- Data for Name: mainapp_statistics; Type: TABLE DATA; Schema: public; Owner: maxsud
--

COPY public.mainapp_statistics (id, created_at, updated_at, total_students, total_graduates, total_employed, avg_duration, avg_start_salary, partners) FROM stdin;
1	2026-01-05 04:31:37.161723+00	2026-01-06 05:57:26.505367+00	3000	2200	1000	7	300	3
\.


--
-- Data for Name: mainapp_status; Type: TABLE DATA; Schema: public; Owner: maxsud
--

COPY public.mainapp_status (id, created_at, updated_at, name_uz, name_en, name_ru) FROM stdin;
1	2026-01-05 05:33:36.594345+00	2026-01-05 05:33:36.594369+00	Test	Test	Test
\.


--
-- Data for Name: mainapp_teacher; Type: TABLE DATA; Schema: public; Owner: maxsud
--

COPY public.mainapp_teacher (id, created_at, updated_at, full_name, bio_uz, bio_en, bio_ru, profession, experience, company, total_students, total_projects, photo, github_link, linkedin_link, twitter_link) FROM stdin;
4	2026-01-08 05:30:34.373437+00	2026-01-08 06:09:56.324325+00	Umidjon Turabov				frontend-dasturlash	3	IT House	260	7	teacher_photos/2.png		https://www.linkedin.com/in/turabov-umidjon-575286289	
5	2026-01-08 05:34:27.920452+00	2026-01-08 06:10:13.246623+00	Noʻmonjonov Shohruhmirzo				Foundation	3	IT House	410	4	teacher_photos/4.png			
3	2026-01-08 05:28:45.446279+00	2026-01-08 06:10:47.006881+00	Muhammadamin Yunusov				Interyer Dizay	8	IT House	1600	50	teacher_photos/5.png			
6	2026-01-10 13:24:59.64717+00	2026-01-10 13:24:59.647203+00	lorem	Lorem ipsum, dolor sit amet consectetur adipisicing elit. Esse, nulla. Eveniet aliquam numquam odit laborum magni molestias quae sint consequatur?	Lorem ipsum, dolor sit amet consectetur adipisicing elit. Esse, nulla. Eveniet aliquam numquam odit laborum magni molestias quae sint consequatur?	Lorem ipsum, dolor sit amet consectetur adipisicing elit. Esse, nulla. Eveniet aliquam numquam odit laborum magni molestias quae sint consequatur?	lorem	24	lorem	234	23	teacher_photos/e325d85a6686a5f5a482c2c580498089.jpg	https://googel.com	https://googel.com	https://googel.com
2	2026-01-08 05:25:01.312646+00	2026-01-14 19:13:26.358611+00	Nodirbek Kuchkarov	Real loyihalar va tijoriy saytlar ustida ishlagan\r\nGoogle, IBM xalqaro sertifikatlariga ega\r\nO‘quvchilarining aksariyati junior darajada ish boshlagan yoki freelancer bo‘lgan	Real loyihalar va tijoriy saytlar ustida ishlagan\r\nGoogle, IBM xalqaro sertifikatlariga ega\r\nO‘quvchilarining aksariyati junior darajada ish boshlagan yoki freelancer bo‘lgan	Real loyihalar va tijoriy saytlar ustida ishlagan\r\nGoogle, IBM xalqaro sertifikatlariga ega\r\nO‘quvchilarining aksariyati junior darajada ish boshlagan yoki freelancer bo‘lgan	Data-analitika	3	IT House	120	6	teacher_photos/IMG_0695.JPG	https://github.com/	https://www.linkedin.com/	https://x.com/
1	2026-01-06 10:19:58.702638+00	2026-01-15 11:21:20.825907+00	Jonibek Turapov	Real loyihalar va tijoriy saytlar ustida ishlagan, Google, IBM xalqaro sertifikatlariga ega ko'p yillik tajribali ustozimiz. Hozirda o‘quvchilarining aksariyati junior darajada ish boshlagan yoki freelancer safitida faoliyat yuritmoqda.	Real loyihalar va tijoriy saytlar ustida ishlagan, Google, IBM xalqaro sertifikatlariga ega ko'p yillik tajribali ustozimiz. Hozirda o‘quvchilarining aksariyati junior darajada ish boshlagan yoki freelancer safitida faoliyat yuritmoqda.	Real loyihalar va tijoriy saytlar ustida ishlagan, Google, IBM xalqaro sertifikatlariga ega ko'p yillik tajribali ustozimiz. Hozirda o‘quvchilarining aksariyati junior darajada ish boshlagan yoki freelancer safitida faoliyat yuritmoqda.	Fullstack developer	5	IT HOUSE	400	20	teacher_photos/umidjon_ustoz_1_6EdOLtI.png			
\.


--
-- Data for Name: mainapp_teacherachievement; Type: TABLE DATA; Schema: public; Owner: maxsud
--

COPY public.mainapp_teacherachievement (id, created_at, updated_at, title_uz, title_en, title_ru, teacher_id) FROM stdin;
\.


--
-- Data for Name: mainapp_teacherskill; Type: TABLE DATA; Schema: public; Owner: maxsud
--

COPY public.mainapp_teacherskill (id, created_at, updated_at, name_uz, name_en, name_ru, teacher_id) FROM stdin;
\.


--
-- Data for Name: mainapp_technology; Type: TABLE DATA; Schema: public; Owner: maxsud
--

COPY public.mainapp_technology (id, created_at, updated_at, name_uz, name_en, name_ru, icon, course_id) FROM stdin;
1	2026-01-08 05:45:43.697881+00	2026-01-08 05:45:43.697922+00	HTML	HTML	HTML	technology_icons/html-5.png	4
2	2026-01-08 05:46:19.735753+00	2026-01-08 05:46:19.7358+00	CSS	CSS	CSS	technology_icons/css3.png	4
3	2026-01-08 05:47:14.713705+00	2026-01-08 05:47:14.713776+00	JavaScript	JavaScript	JavaScript	technology_icons/javascript.png	4
4	2026-01-08 05:47:56.615733+00	2026-01-08 05:47:56.615768+00	GitHub	GitHub	GitHub	technology_icons/github.png	4
5	2026-01-08 05:48:27.114096+00	2026-01-08 05:48:27.114124+00	Bootstrap	Bootstrap	Bootstrap	technology_icons/bootstrap.png	4
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: maxsud
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: maxsud
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: maxsud
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 80, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: maxsud
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: maxsud
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 2, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: maxsud
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: maxsud
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 9, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: maxsud
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 20, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: maxsud
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 19, true);


--
-- Name: mainapp_company_id_seq; Type: SEQUENCE SET; Schema: public; Owner: maxsud
--

SELECT pg_catalog.setval('public.mainapp_company_id_seq', 1, true);


--
-- Name: mainapp_contactmessage_id_seq; Type: SEQUENCE SET; Schema: public; Owner: maxsud
--

SELECT pg_catalog.setval('public.mainapp_contactmessage_id_seq', 1, false);


--
-- Name: mainapp_course_id_seq; Type: SEQUENCE SET; Schema: public; Owner: maxsud
--

SELECT pg_catalog.setval('public.mainapp_course_id_seq', 9, true);


--
-- Name: mainapp_courseabout_id_seq; Type: SEQUENCE SET; Schema: public; Owner: maxsud
--

SELECT pg_catalog.setval('public.mainapp_courseabout_id_seq', 4, true);


--
-- Name: mainapp_coursemodule_id_seq; Type: SEQUENCE SET; Schema: public; Owner: maxsud
--

SELECT pg_catalog.setval('public.mainapp_coursemodule_id_seq', 16, true);


--
-- Name: mainapp_educationabout_id_seq; Type: SEQUENCE SET; Schema: public; Owner: maxsud
--

SELECT pg_catalog.setval('public.mainapp_educationabout_id_seq', 6, true);


--
-- Name: mainapp_moduletheme_id_seq; Type: SEQUENCE SET; Schema: public; Owner: maxsud
--

SELECT pg_catalog.setval('public.mainapp_moduletheme_id_seq', 109, true);


--
-- Name: mainapp_news_id_seq; Type: SEQUENCE SET; Schema: public; Owner: maxsud
--

SELECT pg_catalog.setval('public.mainapp_news_id_seq', 7, true);


--
-- Name: mainapp_statistics_id_seq; Type: SEQUENCE SET; Schema: public; Owner: maxsud
--

SELECT pg_catalog.setval('public.mainapp_statistics_id_seq', 2, true);


--
-- Name: mainapp_status_id_seq; Type: SEQUENCE SET; Schema: public; Owner: maxsud
--

SELECT pg_catalog.setval('public.mainapp_status_id_seq', 1, true);


--
-- Name: mainapp_teacher_id_seq; Type: SEQUENCE SET; Schema: public; Owner: maxsud
--

SELECT pg_catalog.setval('public.mainapp_teacher_id_seq', 6, true);


--
-- Name: mainapp_teacherachievement_id_seq; Type: SEQUENCE SET; Schema: public; Owner: maxsud
--

SELECT pg_catalog.setval('public.mainapp_teacherachievement_id_seq', 1, false);


--
-- Name: mainapp_teacherskill_id_seq; Type: SEQUENCE SET; Schema: public; Owner: maxsud
--

SELECT pg_catalog.setval('public.mainapp_teacherskill_id_seq', 1, false);


--
-- Name: mainapp_technology_id_seq; Type: SEQUENCE SET; Schema: public; Owner: maxsud
--

SELECT pg_catalog.setval('public.mainapp_technology_id_seq', 5, true);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: maxsud
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: maxsud
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: maxsud
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: maxsud
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: maxsud
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: maxsud
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: maxsud
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: maxsud
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: maxsud
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: maxsud
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: maxsud
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: maxsud
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: maxsud
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: maxsud
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: maxsud
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: maxsud
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: maxsud
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: mainapp_company mainapp_company_pkey; Type: CONSTRAINT; Schema: public; Owner: maxsud
--

ALTER TABLE ONLY public.mainapp_company
    ADD CONSTRAINT mainapp_company_pkey PRIMARY KEY (id);


--
-- Name: mainapp_contactmessage mainapp_contactmessage_pkey; Type: CONSTRAINT; Schema: public; Owner: maxsud
--

ALTER TABLE ONLY public.mainapp_contactmessage
    ADD CONSTRAINT mainapp_contactmessage_pkey PRIMARY KEY (id);


--
-- Name: mainapp_course mainapp_course_pkey; Type: CONSTRAINT; Schema: public; Owner: maxsud
--

ALTER TABLE ONLY public.mainapp_course
    ADD CONSTRAINT mainapp_course_pkey PRIMARY KEY (id);


--
-- Name: mainapp_courseabout mainapp_courseabout_pkey; Type: CONSTRAINT; Schema: public; Owner: maxsud
--

ALTER TABLE ONLY public.mainapp_courseabout
    ADD CONSTRAINT mainapp_courseabout_pkey PRIMARY KEY (id);


--
-- Name: mainapp_coursemodule mainapp_coursemodule_pkey; Type: CONSTRAINT; Schema: public; Owner: maxsud
--

ALTER TABLE ONLY public.mainapp_coursemodule
    ADD CONSTRAINT mainapp_coursemodule_pkey PRIMARY KEY (id);


--
-- Name: mainapp_educationabout mainapp_educationabout_pkey; Type: CONSTRAINT; Schema: public; Owner: maxsud
--

ALTER TABLE ONLY public.mainapp_educationabout
    ADD CONSTRAINT mainapp_educationabout_pkey PRIMARY KEY (id);


--
-- Name: mainapp_moduletheme mainapp_moduletheme_pkey; Type: CONSTRAINT; Schema: public; Owner: maxsud
--

ALTER TABLE ONLY public.mainapp_moduletheme
    ADD CONSTRAINT mainapp_moduletheme_pkey PRIMARY KEY (id);


--
-- Name: mainapp_news mainapp_news_pkey; Type: CONSTRAINT; Schema: public; Owner: maxsud
--

ALTER TABLE ONLY public.mainapp_news
    ADD CONSTRAINT mainapp_news_pkey PRIMARY KEY (id);


--
-- Name: mainapp_statistics mainapp_statistics_pkey; Type: CONSTRAINT; Schema: public; Owner: maxsud
--

ALTER TABLE ONLY public.mainapp_statistics
    ADD CONSTRAINT mainapp_statistics_pkey PRIMARY KEY (id);


--
-- Name: mainapp_status mainapp_status_pkey; Type: CONSTRAINT; Schema: public; Owner: maxsud
--

ALTER TABLE ONLY public.mainapp_status
    ADD CONSTRAINT mainapp_status_pkey PRIMARY KEY (id);


--
-- Name: mainapp_teacher mainapp_teacher_pkey; Type: CONSTRAINT; Schema: public; Owner: maxsud
--

ALTER TABLE ONLY public.mainapp_teacher
    ADD CONSTRAINT mainapp_teacher_pkey PRIMARY KEY (id);


--
-- Name: mainapp_teacherachievement mainapp_teacherachievement_pkey; Type: CONSTRAINT; Schema: public; Owner: maxsud
--

ALTER TABLE ONLY public.mainapp_teacherachievement
    ADD CONSTRAINT mainapp_teacherachievement_pkey PRIMARY KEY (id);


--
-- Name: mainapp_teacherskill mainapp_teacherskill_pkey; Type: CONSTRAINT; Schema: public; Owner: maxsud
--

ALTER TABLE ONLY public.mainapp_teacherskill
    ADD CONSTRAINT mainapp_teacherskill_pkey PRIMARY KEY (id);


--
-- Name: mainapp_technology mainapp_technology_pkey; Type: CONSTRAINT; Schema: public; Owner: maxsud
--

ALTER TABLE ONLY public.mainapp_technology
    ADD CONSTRAINT mainapp_technology_pkey PRIMARY KEY (id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: maxsud
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: maxsud
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: maxsud
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: maxsud
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: maxsud
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: maxsud
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: maxsud
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: maxsud
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: maxsud
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: maxsud
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: maxsud
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: maxsud
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: maxsud
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: mainapp_contactmessage_course_id_d89a72f3; Type: INDEX; Schema: public; Owner: maxsud
--

CREATE INDEX mainapp_contactmessage_course_id_d89a72f3 ON public.mainapp_contactmessage USING btree (course_id);


--
-- Name: mainapp_coursemodule_course_id_d3591631; Type: INDEX; Schema: public; Owner: maxsud
--

CREATE INDEX mainapp_coursemodule_course_id_d3591631 ON public.mainapp_coursemodule USING btree (course_id);


--
-- Name: mainapp_moduletheme_module_id_ed0600b5; Type: INDEX; Schema: public; Owner: maxsud
--

CREATE INDEX mainapp_moduletheme_module_id_ed0600b5 ON public.mainapp_moduletheme USING btree (module_id);


--
-- Name: mainapp_news_status_id_e2111b88; Type: INDEX; Schema: public; Owner: maxsud
--

CREATE INDEX mainapp_news_status_id_e2111b88 ON public.mainapp_news USING btree (status_id);


--
-- Name: mainapp_teacherachievement_teacher_id_596da8cc; Type: INDEX; Schema: public; Owner: maxsud
--

CREATE INDEX mainapp_teacherachievement_teacher_id_596da8cc ON public.mainapp_teacherachievement USING btree (teacher_id);


--
-- Name: mainapp_teacherskill_teacher_id_cc9c7782; Type: INDEX; Schema: public; Owner: maxsud
--

CREATE INDEX mainapp_teacherskill_teacher_id_cc9c7782 ON public.mainapp_teacherskill USING btree (teacher_id);


--
-- Name: mainapp_technology_course_id_306562b4; Type: INDEX; Schema: public; Owner: maxsud
--

CREATE INDEX mainapp_technology_course_id_306562b4 ON public.mainapp_technology USING btree (course_id);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: maxsud
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: maxsud
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: maxsud
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: maxsud
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: maxsud
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: maxsud
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: maxsud
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: maxsud
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: maxsud
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: mainapp_contactmessage mainapp_contactmessage_course_id_d89a72f3_fk_mainapp_course_id; Type: FK CONSTRAINT; Schema: public; Owner: maxsud
--

ALTER TABLE ONLY public.mainapp_contactmessage
    ADD CONSTRAINT mainapp_contactmessage_course_id_d89a72f3_fk_mainapp_course_id FOREIGN KEY (course_id) REFERENCES public.mainapp_course(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: mainapp_coursemodule mainapp_coursemodule_course_id_d3591631_fk_mainapp_course_id; Type: FK CONSTRAINT; Schema: public; Owner: maxsud
--

ALTER TABLE ONLY public.mainapp_coursemodule
    ADD CONSTRAINT mainapp_coursemodule_course_id_d3591631_fk_mainapp_course_id FOREIGN KEY (course_id) REFERENCES public.mainapp_course(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: mainapp_moduletheme mainapp_moduletheme_module_id_ed0600b5_fk_mainapp_c; Type: FK CONSTRAINT; Schema: public; Owner: maxsud
--

ALTER TABLE ONLY public.mainapp_moduletheme
    ADD CONSTRAINT mainapp_moduletheme_module_id_ed0600b5_fk_mainapp_c FOREIGN KEY (module_id) REFERENCES public.mainapp_coursemodule(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: mainapp_news mainapp_news_status_id_e2111b88_fk_mainapp_status_id; Type: FK CONSTRAINT; Schema: public; Owner: maxsud
--

ALTER TABLE ONLY public.mainapp_news
    ADD CONSTRAINT mainapp_news_status_id_e2111b88_fk_mainapp_status_id FOREIGN KEY (status_id) REFERENCES public.mainapp_status(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: mainapp_teacherachievement mainapp_teacherachie_teacher_id_596da8cc_fk_mainapp_t; Type: FK CONSTRAINT; Schema: public; Owner: maxsud
--

ALTER TABLE ONLY public.mainapp_teacherachievement
    ADD CONSTRAINT mainapp_teacherachie_teacher_id_596da8cc_fk_mainapp_t FOREIGN KEY (teacher_id) REFERENCES public.mainapp_teacher(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: mainapp_teacherskill mainapp_teacherskill_teacher_id_cc9c7782_fk_mainapp_teacher_id; Type: FK CONSTRAINT; Schema: public; Owner: maxsud
--

ALTER TABLE ONLY public.mainapp_teacherskill
    ADD CONSTRAINT mainapp_teacherskill_teacher_id_cc9c7782_fk_mainapp_teacher_id FOREIGN KEY (teacher_id) REFERENCES public.mainapp_teacher(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: mainapp_technology mainapp_technology_course_id_306562b4_fk_mainapp_course_id; Type: FK CONSTRAINT; Schema: public; Owner: maxsud
--

ALTER TABLE ONLY public.mainapp_technology
    ADD CONSTRAINT mainapp_technology_course_id_306562b4_fk_mainapp_course_id FOREIGN KEY (course_id) REFERENCES public.mainapp_course(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict 8prvZOKtaogpL8f3nPMAP5NWxQNBRwvzhnhP00ngn2kwBl3VqZ83apyTH0wECmc

