version: "3.9"

services:

  db:
    image: postgres:15
    container_name: ithouseedu_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-myproject}
      POSTGRES_USER: ${POSTGRES_USER:-myuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mypassword}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
    restart: unless-stopped

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h localhost -p 5432 -U $POSTGRES_USER -d $POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s


  web:
    build: .
    container_name: ithouseedu_backend
    security_opt:
      - seccomp:unconfined
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    env_file:
      - .env
    ports:
      - "${PORT}:8000"
    depends_on:
      db:
        condition: service_healthy

#  nginx:
#    build: ./nginx
#    container_name: nginx
#    ports:
#      - "8080:80"
#    volumes:
#      - static_volume:/static
#      - media_volume:/media
#    depends_on:
#      web:
#        condition: service_started

volumes:
  postgres_data:
  static_volume:
  media_volume:
