# Generated by Django 5.2.7 on 2025-10-31 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_technology_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='exprerience',
            new_name='experience',
        ),
    ]
