# Generated by Django 5.2.8 on 2026-01-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_contactmessage_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='workers',
        ),
        migrations.AddField(
            model_name='company',
            name='title',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
    ]
