# Generated by Django 5.2.7 on 2025-11-01 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_course_price'),
        ('mainapp', '0003_rename_exprerience_teacher_experience'),
    ]

    operations = [
    ]
