# Generated by Django 5.2.8 on 2026-01-19 05:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_remove_company_workers_company_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='dark_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'svg', 'jpg', 'jpeg', 'webp'])]),
        ),
    ]
