# Generated by Django 5.2.8 on 2026-01-19 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_company_dark_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='course',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='title_en',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='title_ru',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='title_uz',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='coursemodule',
            name='title_en',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='coursemodule',
            name='title_ru',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='coursemodule',
            name='title_uz',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='moduletheme',
            name='title_en',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='moduletheme',
            name='title_ru',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='moduletheme',
            name='title_uz',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='status',
            name='name_en',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='status',
            name='name_ru',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='status',
            name='name_uz',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='profession',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='teacherskill',
            name='name_en',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='teacherskill',
            name='name_ru',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='teacherskill',
            name='name_uz',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='technology',
            name='name_en',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='technology',
            name='name_ru',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='technology',
            name='name_uz',
            field=models.CharField(max_length=255),
        ),
    ]
