# Generated by Django 5.2.8 on 2026-01-20 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_contactmessage_course_alter_course_title_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='courseabout',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='coursemodule',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='educationabout',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='moduletheme',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='technology',
            options={'ordering': ['created_at']},
        ),
    ]
