# Generated by Django 5.2.8 on 2025-11-22 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_company_logo_alter_course_banner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
